# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReimaginedOctoSuccotash < Formula
  desc "reimagined-octo-succotash homebrew tap."
  homepage "https://github.com/taspotts/reimagined-octo-succotash"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.7.0/reimagined-octo-succotash_Darwin_x86_64.tar.gz"
      sha256 "bec8e80dd85cc22615b3f4fb981837821ffd344dcc2daf9bc37c0d4dc1a33a1a"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.7.0/reimagined-octo-succotash_Darwin_arm64.tar.gz"
      sha256 "9818d6518c70ee1ded048b73b673514f0fa54600da485cf8703604d97dbe7f1c"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.7.0/reimagined-octo-succotash_Linux_x86_64.tar.gz"
      sha256 "64892783949fa5e1b66b25a34f59b35b6d457baa07a2c79a1f2dfa5b21a6012a"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
  end
end
