# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReimaginedOctoSuccotash < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.4.0/reimagined-octo-succotash_Darwin_arm64.tar.gz"
      sha256 "ae9d1cffe5f6e05e4aacb9fa38f1c66ac29efa32f22d97bac99b90afab71128b"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.4.0/reimagined-octo-succotash_Darwin_x86_64.tar.gz"
      sha256 "cf0bcaa21ed2dd16a506c099f5ace8045d6a3534dd203319106ce61ba7b15f4f"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.4.0/reimagined-octo-succotash_Linux_x86_64.tar.gz"
      sha256 "11b66f0a1e697c7f669be8a326a53298cbc26987e63fa91c2bbdc3bf58f293a8"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.4.0/reimagined-octo-succotash_Linux_arm64.tar.gz"
      sha256 "2e2152ae7ebd51f23eff8af01550d8e1b2dbb805281639983f003b0fba693427"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
  end
end
