# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReimaginedOctoSuccotash < Formula
  desc "reimagined-octo-succotash homebrew tap."
  homepage "https://github.com/taspotts/reimagined-octo-succotash"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.5.0/reimagined-octo-succotash_Darwin_arm64.tar.gz"
      sha256 "4e9879b87c7faaf4a5069ba5beb63b3b96d96aff41059cc0356c1a1925f787d5"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.5.0/reimagined-octo-succotash_Darwin_x86_64.tar.gz"
      sha256 "4ae1916c3d24e00ec96c8a6e15a5a77f2ef80912b4b6a319cfa12faa7b599778"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.5.0/reimagined-octo-succotash_Linux_x86_64.tar.gz"
      sha256 "1ba335865c1f1faef6bbae0585f83fe80328f922169001a1f6c17ab82ce0ec28"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/taspotts/reimagined-octo-succotash/releases/download/v0.5.0/reimagined-octo-succotash_Linux_arm64.tar.gz"
      sha256 "2f7a5c77a48389022757d287b49368c9d897cd3628543833fe8832def01ca553"

      def install
        bin.install "reimagined-octo-succotash"
      end
    end
  end
end
